# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Commander' do

platform :ios, '6.1'
pod 'SDWebImage', '~>3.6'

end

target 'CommanderTests' do

end

